# Generated by `rjournal_article()` using `knitr::purl()`: do not edit by hand
# Please edit sandbox.Rmd to modify this file

## ----include=FALSE------------------------------------------------------------
knitr::opts_chunk$set(out.width = "\\textwidth")



## ---- warning=FALSE, message=FALSE, include = FALSE,eval=FALSE, comment='\n', echo=FALSE, results='asis'----

 cat(readLines('skeleton.Rmd'),sep='\n') #or results='hold'/'asis/tex? 'asis' doesn't show YAML header


## ----fig-skeleton, echo=FALSE, fig.cap='A comparison of minimal examples of a typical .Rmd document and a .Rmd document for an interactive sandbox app.', fig.subcap=c('A typical .Rmd file', 'A sandbox app .Rmd file'), fig.ncol = 2, fig.align='center', out.width='.49\\linewidth'----
knitr::include_graphics('skeleton-md.png')
knitr::include_graphics('skeleton.png')


## ----fig2, echo=FALSE, fig.cap='A screenshot of the GB rainfall interactive notebook site. The main feature is the code box. When the site loads, the code that generates the published version of the figure is in the box and the published version of the figure is below it. Users can make edits and re-run the code in the code box and the figure will update accordingly. Users can use the "Start Over" button to see the published version of the code at any point without refreshing the entire site.'----
knitr::include_graphics('GB_notebook_screenshot.png')


## ----fig1, echo=FALSE, fig.cap='The various levels of abstraction of various types of R documents. Our approach fills nicely the gap between R Markdown or Jupyter notebooks and Shiny apps.'----
knitr::include_graphics('learnr_abstraction.png')


## ---- include=FALSE ,warning=FALSE, message=FALSE, comment='\n'---------------
#cat(readLines('/data/rain_pattern/results_tut.Rmd'),sep='\n')

